export const GET_INTERVIEWS = 'GET_INTERVIEWS'
export const GET_INTERVIEW = 'GET_INTERVIEW'
export const CREATE_INTERVIEW = 'CREATE_INTERVIEW'
export const EDIT_INTERVIEW = 'EDIT_INTERVIEW'
export const UPDATE_INTERVIEW = 'UPDATE_INTERVIEW'

export const GET_PARTICIPANTS = 'GET_PARTICIPANTS'
export const ADD_PARTICIPANT = 'ADD_PARTICIPANT'
export const EDIT_PARTICIPANT = 'EDIT_PARTICIPANT'